#!/usr/bin/env python3

from copy import deepcopy
from pathlib import Path


BASE_CONFIG = {
    "DATALOADER": {
        "TRAIN_X": {"BATCH_SIZE": 8},
        "TRAIN_U": {"SAME_AS_X": True, "BATCH_SIZE": 8},
        "TEST": {"BATCH_SIZE": 100},
        "NUM_WORKERS": 8,
    },
    "INPUT": {
        "SIZE": "(224, 224)",
        "INTERPOLATION": "bicubic",
        "PIXEL_MEAN": [0.48145466, 0.4578275, 0.40821073],
        "PIXEL_STD": [0.26862954, 0.26130258, 0.27577711],
        "TRANSFORMS": ["random_resized_crop", "random_flip", "normalize"],
    },
    "OPTIM": {
        "NAME": "sgd",
        "LR": 0.002,
        "MAX_EPOCH": 10,
        "LR_SCHEDULER": "cosine",
        "WARMUP_EPOCH": 1,
        "WARMUP_TYPE": "constant",
        "WARMUP_CONS_LR": 1e-5,
    },
    "TRAIN": {
        "PRINT_FREQ": 20,
        "COUNT_ITER": "smaller_one",
    },
    "MODEL": {"BACKBONE": {"NAME": "ViT-B/16"}},
    "TRAINER": {
        "GSPA_LEGACY": {
            "N_CTX": 4,
            "CTX_INIT": "a photo of a",
            "PREC": "fp16",
            "INJECT_AFTER_BLOCK": 4,
            "STATS_SCOPE": "all_tokens",
            "EPS": 1e-6,
            "GATE_HIDDEN_RATIO": 16,
            "GATE_INIT_BIAS": 3.0,
            "LABEL_SMOOTHING": 0.1,
            "TRAIN_VISUAL_LAST_N": 3,
            "USE_ALIGN_LOSS": False,
            "USE_TARGET_ENTROPY": False,
            "USE_KL": False,
            "TRAIN_LOGIT_SCALE": False,
            "ABLATION": {
                "EXP_NAME": "legacy_full",
                "GATE_MODE": "learned",
                "FIXED_GATE_VALUE": 0.95,
                "TRAIN_VISION_LAST3": True,
                "STYLE_MODE": "cross",
                "STATS_SCOPE": "all_tokens",
            },
            "LR_RATIO": {
                "CTX": 1.0,
                "METANET": 1.0,
                "GATE": 1.0,
                "VISION_LAST": 0.1,
                "VISION_POST_LN": 0.1,
                "VISUAL_PROJ": 0.1,
                "LOGIT_SCALE": 0.0,
            },
            "DEBUG": {"PRINT_ONCE": False},
        }
    },
}


ABLATIONS = {
    "office31_L0_full.yaml": {
        "EXP_NAME": "L0_full",
        "GATE_MODE": "learned",
        "FIXED_GATE_VALUE": 0.95,
        "TRAIN_VISION_LAST3": True,
        "STYLE_MODE": "cross",
        "STATS_SCOPE": "all_tokens",
    },
    "office31_L1_fixed_gate.yaml": {
        "EXP_NAME": "L1_fixed_gate",
        "GATE_MODE": "fixed",
        "FIXED_GATE_VALUE": 0.95,
        "TRAIN_VISION_LAST3": True,
        "STYLE_MODE": "cross",
        "STATS_SCOPE": "all_tokens",
    },
    "office31_L2_normal_only.yaml": {
        "EXP_NAME": "L2_normal_only",
        "GATE_MODE": "normal_only",
        "FIXED_GATE_VALUE": 1.0,
        "TRAIN_VISION_LAST3": True,
        "STYLE_MODE": "cross",
        "STATS_SCOPE": "all_tokens",
    },
}


def format_scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return f'"{value}"'
    return str(value)


def dump_yaml(node, indent=0):
    lines = []
    prefix = " " * indent

    if isinstance(node, dict):
        for key, value in node.items():
            if isinstance(value, dict):
                lines.append(f"{prefix}{key}:")
                lines.extend(dump_yaml(value, indent + 2))
            elif isinstance(value, list):
                inline = ", ".join(format_scalar(item) for item in value)
                lines.append(f"{prefix}{key}: [{inline}]")
            else:
                lines.append(f"{prefix}{key}: {format_scalar(value)}")
    else:
        raise TypeError(f"Unsupported YAML node: {type(node)!r}")

    return lines


def make_config(spec):
    cfg = deepcopy(BASE_CONFIG)
    ablation = cfg["TRAINER"]["GSPA_LEGACY"]["ABLATION"]
    ablation.update(spec)
    cfg["TRAINER"]["GSPA_LEGACY"]["STATS_SCOPE"] = spec["STATS_SCOPE"]
    return cfg


def main():
    repo_root = Path(__file__).resolve().parents[2]
    output_dir = repo_root / "configs" / "trainers" / "GSPA_LEGACY" / "ablation"
    output_dir.mkdir(parents=True, exist_ok=True)

    for filename, spec in ABLATIONS.items():
        cfg = make_config(spec)
        content = "# Auto-generated by scripts/gspa_legacy_ablation/make_ablation_configs.py\n"
        content += "\n".join(dump_yaml(cfg)) + "\n"
        output_path = output_dir / filename
        output_path.write_text(content)
        print(output_path.relative_to(repo_root))


if __name__ == "__main__":
    main()
